<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleSeeder extends Seeder
{
    public function run(): void
    {
        $guard = PermissionSeeder::GUARD;

        $superAdmin = Role::firstOrCreate(['name' => 'super-admin', 'guard_name' => $guard]);
        $administrador = Role::firstOrCreate(['name' => 'administrador', 'guard_name' => $guard]);
        $veterinario = Role::firstOrCreate(['name' => 'veterinario', 'guard_name' => $guard]);
        $trabajador = Role::firstOrCreate(['name' => 'trabajador', 'guard_name' => $guard]);

        $allPermissions = Permission::where('guard_name', $guard)->pluck('name')->toArray();

        $superAdmin->syncPermissions($allPermissions);

        $administrador->syncPermissions([
            'usuarios.view',
            'usuarios.create',
            'usuarios.update',
            'usuarios.delete',
            'usuarios.restore',
            'usuarios.activate',
            'socios.view',
            'socios.create',
            'socios.update',
            'socios.delete',
            'socios.restore',
            'socios.activate',
            'tipos_persona.view',
            'tipos_persona.create',
            'tipos_persona.update',
            'tipos_persona.delete',
            'compras.view',
            'compras.create',
            'compras.update',
            'compras.authorize',
            'razas.view',
            'razas.create',
            'razas.update',
            'razas.delete',
            'razas.restore',
            'razas.activate',
            'categorias_animales.view',
            'categorias_animales.create',
            'categorias_animales.update',
            'categorias_animales.delete',
            'categorias_animales.restore',
            'categorias_animales.activate',
            'vacunas.view',
            'vacunas.create',
            'vacunas.update',
            'vacunas.delete',
            'vacunas.restore',
            'vacunas.activate',
            'estados_productivos.view',
            'estados_productivos.create',
            'estados_productivos.update',
            'estados_productivos.delete',
            'estados_productivos.restore',
            'estados_productivos.activate',
            'tipos_eventos_sanitarios.view',
            'tipos_eventos_sanitarios.create',
            'tipos_eventos_sanitarios.update',
            'tipos_eventos_sanitarios.delete',
            'tipos_eventos_sanitarios.restore',
            'tipos_eventos_sanitarios.activate',
            'tipos_movimientos.view',
            'tipos_movimientos.create',
            'tipos_movimientos.update',
            'tipos_movimientos.delete',
            'tipos_movimientos.restore',
            'tipos_movimientos.activate',
            'tipos_alertas.view',
            'tipos_alertas.create',
            'tipos_alertas.update',
            'tipos_alertas.delete',
            'tipos_alertas.restore',
            'tipos_alertas.activate',
            'establecimientos.view',
            'establecimientos.create',
            'establecimientos.update',
            'establecimientos.delete',
            'establecimientos.restore',
            'establecimientos.activate',
            'potreros.view',
            'potreros.create',
            'potreros.update',
            'potreros.delete',
            'potreros.restore',
            'potreros.activate',
            'lotes.view',
            'lotes.create',
            'lotes.update',
            'lotes.delete',
            'lotes.restore',
            'lotes.activate',
            'animales.view',
            'animales.create',
            'animales.update',
            'animales.delete',
            'animales.restore',
            'animales.activate',
            'animales.export',
            'pesajes.view',
            'pesajes.create',
            'sanitario.view',
            'sanitario.create',
            'sanitario.update',
            'sanitario.delete',
            'movimientos.view',
            'movimientos.create',
            'movimientos.update',
            'movimientos.delete',
            'movimientos.approve',
            'reproduccion.view',
            'reproduccion.create',
            'reproduccion.update',
            'reproduccion.delete',
            'indicadores.view',
            'indicadores.manage',
            'alertas.view',
            'alertas.manage',
            'alertas.resolve',
            'reportes.view',
            'reportes.export',
            'reportes.manage',
            'auditoria.view',
        ]);

        $veterinario->syncPermissions([
            'socios.view',
            'socios.create',
            'tipos_persona.view',
            'razas.view',
            'vacunas.view',
            'estados_productivos.view',
            'tipos_eventos_sanitarios.view',
            'tipos_movimientos.view',
            'tipos_alertas.view',
            'establecimientos.view',
            'potreros.view',
            'lotes.view',
            'animales.view',
            'animales.create',
            'animales.update',
            'animales.export',
            'pesajes.view',
            'pesajes.create',
            'sanitario.view',
            'sanitario.create',
            'sanitario.update',
            'movimientos.view',
            'movimientos.create',
            'reproduccion.view',
            'reproduccion.create',
            'reproduccion.update',
            'indicadores.view',
            'alertas.view',
            'alertas.resolve',
            'reportes.view',
            'reportes.export',
        ]);

        $trabajador->syncPermissions([
            'socios.view',
            'socios.create',
            'tipos_persona.view',
            'compras.view',
            'compras.create',
            'razas.view',
            'vacunas.view',
            'estados_productivos.view',
            'tipos_eventos_sanitarios.view',
            'tipos_movimientos.view',
            'tipos_alertas.view',
            'establecimientos.view',
            'potreros.view',
            'lotes.view',
            'animales.view',
            'animales.create',
            'pesajes.view',
            'pesajes.create',
            'sanitario.view',
            'movimientos.view',
            'movimientos.create',
            'reproduccion.view',
            'indicadores.view',
            'alertas.view',
            'alertas.resolve',
            'reportes.view',
        ]);
    }
}
